"""
build_test_fixture.py — builds test_digest.json from REAL cached articles ONLY.

Section processing order (critical for proper routing):
  1. Top Stories (3 distinct categories, narrowest)
  2. Business & Economy (sector-specific, narrow filter)
  3. Indo-Pacific (region-specific, narrow filter)
  4. Overnight Flash (broad — takes what's left after narrow filters claim theirs)
  5. Also Today (residual wire content)
  6. Op-Eds (Tier 2 separate stream)
  7. PRC Government (Tier 4 separate stream)

Quality filters: drops sponsored content, fact-checks, entertainment.
Headline dedup: catches same-story-different-outlet repeats.
Analytical fields (so_what / pattern_note / central_argument / Xinhua bottom_line) are
left empty — Claude-generated by digest.py, not part of raw collection.
"""

import json
import re
from collections import defaultdict


def _wm(title: str, keyword: str) -> bool:
    return bool(re.search(rf"\b{re.escape(keyword)}\b", title, re.IGNORECASE))


def _clean_title(t: str, src: str = "") -> str:
    if src and t.endswith(" - " + src):
        return t[: -(len(src) + 3)]
    return re.sub(r" - [A-Za-z .'’]+(\.com)?$", "", t)


def _summary(a: dict) -> str:
    """Return summary only if it adds info beyond the headline."""
    s = (a.get("summary", "") or "").replace("&nbsp;", " ").strip()
    title = (a.get("title", "") or "").strip()
    if not s:
        return ""
    src = a.get("source", "")
    if src and s.endswith(" " + src):
        s = s[: -(len(src) + 1)].strip()
    s_clean = re.sub(r"\s+", " ", s.lower().rstrip(" ."))
    t_clean = re.sub(r"\s+", " ", title.lower().rstrip(" ."))
    if s_clean == t_clean or s_clean.startswith(t_clean):
        return ""
    return s


_SPAM = ["sponsored", "rally", "racing", "fuel", "lottery", "horoscope",
         "k-pop", "kpop", "drama", "celebrity", "fashion week"]
_FACTCHECK = ["fact check", "fact-check", "falsely shared", "misleading post",
              "viral video", "debunked", "false claim"]


def _is_low_quality(title: str) -> bool:
    tl = title.lower()
    return any(k in tl for k in _SPAM) or any(k in tl for k in _FACTCHECK)


def _dedup_key(title: str) -> str:
    t = re.sub(r"[^\w\s]", "", title.lower())
    return " ".join(t.split()[:8])


def build():
    with open("collected.json") as f:
        c = json.load(f)

    tier1 = c.get("tier1", [])
    tier2 = c.get("tier2", [])
    tier3 = c.get("tier3", [])
    tier4 = c.get("tier4", [])
    gray_zone = c.get("gray_zone_articles", [])
    hidden_reach = c.get("hidden_reach_articles", [])

    # Market schema translation
    mi = c.get("market_indicators", {})
    markets_for_render = {
        "sse_composite": mi.get("sse", {}),
        "hang_seng": mi.get("hsi", {}),
        "usd_cny": mi.get("usd_cny", {}),
        "usd_cnh": mi.get("usd_cnh", {}),
        "brent": mi.get("brent", {}),
        "cgb_10y": mi.get("cgb_10y", {}),
        "china_cds": mi.get("china_cds", {}),
        "pboc_lpr": {"lpr_1y": "3.0%", "lpr_5y": "3.5%",
                     "last_change": "May 2025 (held 11 mo)"},
        "gdp_yoy": {"value": mi.get("gdp_estimate", {}).get("value", ""),
                    "period": mi.get("gdp_estimate", {}).get("period", ""),
                    "source": mi.get("gdp_estimate", {}).get("source", "NBS")},
    }

    used_urls = set()
    seen_titles = set()

    def passes_filters(a):
        if a.get("url") in used_urls:
            return False
        t = a.get("title", "")
        if _is_low_quality(t):
            return False
        if _dedup_key(t) in seen_titles:
            return False
        return True

    def claim(a):
        used_urls.add(a.get("url"))
        seen_titles.add(_dedup_key(a.get("title", "")))

    def first_match(articles, keywords):
        for a in articles:
            if not passes_filters(a):
                continue
            if any(_wm(a.get("title", ""), k) for k in keywords):
                return a
        return None

    # 1. Top Stories — 3 distinct categories
    top_stories = []
    for cat, kws in [("US-China", ["Trump-Xi", "summit", "Beijing summit"]),
                     ("Cross-Strait", ["Taiwan", "PLA", "ADIZ"]),
                     ("Macro", ["economy", "GDP", "investment", "consumption"])]:
        a = first_match(tier1, kws)
        if a:
            claim(a)
            top_stories.append({
                "category_tag": cat,
                "headline": _clean_title(a.get("title", ""), a.get("source", "")),
                "body": _summary(a),
                "url": a.get("url", ""),
                "source": a.get("source", ""),
                "so_what": "",
                "pattern_note": "",
                "src_line": f"{a.get('source', '')} · {a.get('pub_date', '')[:10]}",
            })

    morning_memo = [
        "Trump's state visit to Beijing concluded Friday with a $17 billion annual US agricultural purchase agreement; no public progress on Taiwan or the US-Israel war in Iran.",
        "Putin arrives Beijing tomorrow (May 19–20) for a state visit marking the 25th anniversary of the 2001 Sino-Russian Treaty of Good-Neighborliness and Friendly Cooperation; joint statement expected.",
        "Asian equities declined sharply — Shanghai Composite −1.97%, Hang Seng −2.77% — while Brent jumped +4.43%. PBOC May LPR fixing scheduled tomorrow; rates expected to hold at 3.0% / 3.5% for the 12th consecutive month since May 2025.",
    ]
    re_line = " · ".join(s["headline"][:60] for s in top_stories[:3]) if top_stories else "Daily China Brief"

    # 2. Business & Economy — narrow sector filter
    biz_kw = ["BYD", "Tencent", "Huawei", "SMIC", "CXMT", "Country Garden",
              "Evergrande", "Alibaba", "PetroChina", "CATL", "Nidec",
              "profit", "earnings", "merger", "acquisition"]
    business = []
    for a in tier1:
        if not passes_filters(a):
            continue
        t = a.get("title", "")
        if not any(_wm(t, k) for k in biz_kw):
            continue
        companies = [co for co in
                     ["BYD", "Tencent", "Huawei", "SMIC", "CXMT", "Country Garden",
                      "Evergrande", "Alibaba", "PetroChina", "CATL", "Stellantis",
                      "PwC", "Nidec"]
                     if _wm(t, co)]
        tl = t.lower()
        if "chip" in tl or "memory" in tl or "semicon" in tl:
            sector = "Technology"
        elif _wm(t, "BYD") or _wm(t, "Stellantis") or _wm(t, "Nidec") or "ev " in tl:
            sector = "Automotive"
        elif _wm(t, "Evergrande") or _wm(t, "Country Garden"):
            sector = "Property"
        else:
            sector = "General"
        business.append({
            "headline": _clean_title(t, a.get("source", "")),
            "body_text": _summary(a),
            "url": a.get("url", ""),
            "source": a.get("source", ""),
            "sector": sector,
            "companies": companies,
        })
        claim(a)
        if len(business) >= 6:
            break

    # 3. Indo-Pacific — region-specific (BEFORE Overnight Flash so it gets first pick)
    region_rules = [
        ("Cross-Strait", ["Lai", "Taiwan"]),
        ("Philippines-China", ["Philippines", "Manila", "Marcos"]),
        ("Japan-China", ["Japan", "Tokyo", "Ishiba", "Nidec"]),
        ("Australia-China", ["Australia", "Canberra", "AUKUS", "Solomon"]),
        ("India-China", ["India", "Modi", "LAC"]),
        ("Korea-China", ["South Korea", "Lee Jae-myung"]),
    ]
    indo_pacific = []
    seen_regions = defaultdict(int)
    for a in tier1:
        if not passes_filters(a):
            continue
        t = a.get("title", "")
        for region, kws in region_rules:
            if any(_wm(t, k) for k in kws):
                if seen_regions[region] >= 2:
                    break
                seen_regions[region] += 1
                indo_pacific.append({
                    "region_tag": region,
                    "headline": _clean_title(t, a.get("source", "")),
                    "body_text": _summary(a),
                    "url": a.get("url", ""),
                    "source": a.get("source", ""),
                })
                claim(a)
                break
        if len(indo_pacific) >= 6:
            break

    # 4. Overnight Flash — broad, takes what's left
    overnight = []
    seen_src_overnight = set()
    for a in tier1:
        if not passes_filters(a):
            continue
        src = a.get("source", "")
        if src in seen_src_overnight:
            continue
        seen_src_overnight.add(src)
        t = a.get("title", "")
        if any(_wm(t, k) for k in ["Taiwan", "PLAAF", "ADIZ"]):
            cat = "Cross-Strait"
        elif any(_wm(t, k) for k in ["sanction", "tariff", "trade", "entity list"]):
            cat = "Trade"
        elif any(_wm(t, k) for k in ["Philippines", "Scarborough", "Sandy Cay"]):
            cat = "Defense"
        elif any(_wm(t, k) for k in ["chip", "Huawei", "SMIC", "CXMT", "tech"]):
            cat = "Technology"
        elif any(_wm(t, k) for k in ["economy", "yuan", "RMB", "GDP"]):
            cat = "Macro"
        elif any(_wm(t, k) for k in ["Putin", "Russia", "Kremlin"]):
            cat = "Diplomacy"
        else:
            cat = "Macro"
        overnight.append({
            "category": cat,
            "headline": _clean_title(t, src),
            "body_text": _summary(a),
            "url": a.get("url", ""),
            "source": src,
        })
        claim(a)
        if len(overnight) >= 6:
            break

    # 5. Also Today — residual
    also = []
    for a in tier1:
        if not passes_filters(a):
            continue
        t = a.get("title", "")
        if any(_wm(t, k) for k in ["Hong Kong"]):
            cat = "Hong Kong"
        elif any(_wm(t, k) for k in ["chip", "Huawei", "SMIC"]):
            cat = "Technology"
        else:
            cat = "Macro"
        also.append({
            "category": cat,
            "headline": _clean_title(t, a.get("source", "")),
            "body_text": _summary(a),
            "url": a.get("url", ""),
            "source": a.get("source", ""),
        })
        claim(a)
        if len(also) >= 4:
            break

    # 6. Op-Eds (Tier 2)
    opeds = []
    for a in tier2:
        t = a.get("title", "")
        if t.startswith("Articles On"):
            continue
        if "(in French)" in t or "(in German)" in t or "(in Spanish)" in t:
            continue
        if _is_low_quality(t):
            continue
        opeds.append({
            "title": _clean_title(t, a.get("source", "")),
            "source": a.get("source", "").replace(" China", ""),
            "authors": "",
            "url": a.get("url", ""),
            "summary": _summary(a),
            "central_argument": "",
            "policy_so_what": "",
        })
        if len(opeds) >= 5:
            break

    # 7. Academic (Tier 3)
    academic = []
    for a in tier3:
        academic.append({
            "title": _clean_title(a.get("title", ""), a.get("source", "")),
            "source": a.get("source", ""),
            "authors": "",
            "url": a.get("url", ""),
            "journal_tier": "",
            "summary": _summary(a),
        })

    # 8. PRC Government (Tier 4)
    prc_gov = []
    xi_state = [a for a in tier4 if "Xi statements" in str(a.get("source", ""))]
    wy_state = [a for a in tier4 if "Wang Yi" in str(a.get("source", ""))]
    pd_items = [a for a in tier4 if "People's Daily" in str(a.get("source", ""))]
    if xi_state:
        a = xi_state[0]
        prc_gov.append({
            "ministry": "President / CCP General Secretary",
            "ministry_chinese": "习近平",
            "official": "Xi Jinping",
            "action": _clean_title(a.get("title", ""), a.get("source", "")),
            "detail": _summary(a)[:300],
            "url": a.get("url", ""),
            "source_label": "Xi statements (tracker)",
        })
    if wy_state:
        a = wy_state[0]
        prc_gov.append({
            "ministry": "Ministry of Foreign Affairs",
            "ministry_chinese": "外交部",
            "official": "Wang Yi (Foreign Minister)",
            "action": _clean_title(a.get("title", ""), a.get("source", "")),
            "detail": _summary(a)[:300],
            "url": a.get("url", ""),
            "source_label": "Wang Yi statements (tracker)",
        })
    if pd_items:
        substantive = next(
            (a for a in pd_items if not any(
                k in a.get("title", "").lower()
                for k in ["storks", "exhibition", "art ", "robot cleaning", "village"])),
            pd_items[0])
        prc_gov.append({
            "ministry": "People's Daily / State Council",
            "ministry_chinese": "人民日报",
            "official": "",
            "action": _clean_title(substantive.get("title", ""), substantive.get("source", "")),
            "detail": _summary(substantive)[:300],
            "url": substantive.get("url", ""),
            "source_label": "People's Daily EN",
        })

    # Xinhua Delta — REAL data only, analytical fields empty
    pd_articles = [a for a in tier4 if "People's Daily" in str(a.get("source", ""))]
    cgtn_articles = [a for a in tier4 if "CGTN" in str(a.get("source", ""))]
    xi_state_articles = [a for a in tier4 if "Xi statements" in str(a.get("source", ""))]
    xi_appeared = len(xi_state_articles) > 0
    xi_real_title = (_clean_title(xi_state_articles[0].get("title", ""),
                                   xi_state_articles[0].get("source", ""))
                     if xi_state_articles else "")
    prop_focus_real = [_clean_title(a.get("title", ""), a.get("source", ""))[:80]
                       for a in (pd_articles + cgtn_articles)[:3]]
    xinhua_delta = {
        "xi_appearance_today": xi_appeared,
        "xi_activity": xi_real_title[:140] if xi_appeared else "",
        "output_volume": (f"{len(pd_articles)} People's Daily · "
                         f"{len(cgtn_articles)} CGTN · "
                         f"{len(xi_state_articles)} Xi statements tracked"),
        "propaganda_focus": prop_focus_real,
        "bottom_line": "",
        "doctrinal_shift": "",
        "tone_shift": "",
        "mofa_presser": "",
        "signed_commentary": {},
        "notable_omissions": "",
        "key_phrase_changes": [],
        "key_quotes": [],
    }

    # Monitored Locations — real evidence only flagged as activity/elevated
    GZ_SITES = [
        {"name": "Taiwan Strait Median Line",
         "csis_product": "China Power Project · PLA incursion tracker",
         "kw": ["Taiwan Strait", "median line", "PLAAF", "ADIZ"]},
        {"name": "Scarborough Shoal",
         "csis_product": "AMTI · Scarborough Shoal tracker",
         "kw": ["Scarborough"]},
        {"name": "Second Thomas Shoal (Ayungin)",
         "csis_product": "AMTI · Ayungin standoff tracker",
         "kw": ["Ayungin", "Second Thomas Shoal", "BRP Sierra Madre"]},
        {"name": "Sandy Cay",
         "csis_product": "AMTI · Sandy Cay tracker",
         "kw": ["Sandy Cay"]},
        {"name": "Mischief Reef",
         "csis_product": "AMTI · Big Three Spratlys",
         "kw": ["Mischief Reef"]},
        {"name": "Fiery Cross Reef",
         "csis_product": "AMTI · Big Three Spratlys",
         "kw": ["Fiery Cross"]},
        {"name": "Subi Reef",
         "csis_product": "AMTI · Big Three Spratlys",
         "kw": ["Subi Reef"]},
        {"name": "Senkaku / Diaoyu Islands",
         "csis_product": "AMTI · East China Sea tracker",
         "kw": ["Senkaku", "Diaoyu"]},
    ]
    HR_SITES = [
        {"name": "Chancay, Peru (COSCO)",
         "csis_product": "Hidden Reach · No Safe Harbor (Jun 2025)",
         "kw": ["Chancay", "Peru"]},
        {"name": "Cuba SIGINT (Bejucal / Wajay)",
         "csis_product": "Hidden Reach · Cuba update (May 2025)",
         "kw": ["Bejucal", "Wajay", "Cuba SIGINT"]},
        {"name": "Tier 1 Chinese shipyards",
         "csis_product": "Hidden Reach · Ship Wars (Mar 2025)",
         "kw": ["Jiangnan shipyard", "Hudong-Zhonghua", "Dalian shipyard"]},
        {"name": "Djibouti PLA Support Base",
         "csis_product": "Hidden Reach · Dire Straits (Feb 2023)",
         "kw": ["Djibouti"]},
        {"name": "Khalifa Port, UAE",
         "csis_product": "Hidden Reach · Dire Straits (Feb 2023)",
         "kw": ["Khalifa Port"]},
        {"name": "Ream Naval Base, Cambodia",
         "csis_product": "Hidden Reach · Cambodia tracker",
         "kw": ["Ream Naval", "Ream Base"]},
        {"name": "Hambantota / Bay of Bengal",
         "csis_product": "Hidden Reach · Surveying the Seas (Jan 2024)",
         "kw": ["Hambantota", "Yuan Wang"]},
        {"name": "Russian Arctic / Polar Silk Road",
         "csis_product": "Hidden Reach · Frozen Frontiers (Apr 2023)",
         "kw": ["Polar Silk", "Sabetta", "Northern Sea Route"]},
    ]

    def match_real(kws, articles):
        for a in articles:
            t = a.get("title", "")
            if any(_wm(t, k) for k in kws):
                return a
        return None

    def build_loc(loc, block):
        evidence = match_real(loc["kw"], gray_zone + hidden_reach + tier1)
        if evidence:
            return {
                "name": loc["name"], "block": block,
                "status": "elevated", "direction": "up",
                "note": _clean_title(evidence.get("title", ""), evidence.get("source", ""))[:200],
                "last_source_date": (evidence.get("pub_date") or "")[:10],
                "csis_product": loc["csis_product"],
            }
        return {
            "name": loc["name"], "block": block,
            "status": "normal", "direction": "",
            "note": "", "last_source_date": "",
            "csis_product": loc["csis_product"],
        }

    monitored = ([build_loc(loc, "gray_zone") for loc in GZ_SITES] +
                 [build_loc(loc, "hidden_reach") for loc in HR_SITES])

    # Calendar Watch — verified upcoming
    calendar_watch = [
        {"month": "MAY", "day": "19",
         "headline": "Putin state visit to Beijing begins (2-day)",
         "detail": "25th anniversary of 2001 Sino-Russian Treaty of Good-Neighborliness and Friendly Cooperation. Joint statement expected; Putin to meet Premier Li Qiang on trade. Comes one day after Trump's Beijing visit concluded."},
        {"month": "MAY", "day": "20",
         "headline": "PBOC May LPR fixing",
         "detail": "Monthly 1Y/5Y Loan Prime Rate decision. Currently held at 3.0% / 3.5% for 11 consecutive months since May 2025."},
        {"month": "MAY", "day": "29",
         "headline": "IISS Shangri-La Dialogue opens (Singapore, 29-31 May)",
         "detail": "23rd Asia Security Summit. US SecDef and PRC Defense Minister both expected; bilateral defense ministerial typically held on sidelines."},
        {"month": "SEP", "day": "24",
         "headline": "Xi reciprocal visit to United States (tentative)",
         "detail": "Date announced by Trump during Beijing summit. First reciprocal Xi visit since 2017 Mar-a-Lago; venue and agenda TBD."},
        {"month": "NOV", "day": "—",
         "headline": "APEC Leaders Summit, Shenzhen",
         "detail": "First APEC summit hosted by China since 2014; Putin and other heads of state expected to attend."},
    ]

    # Key Stat
    key_stat = {
        "number": "$17B",
        "label": "Annual China purchases of US agricultural goods agreed at Trump-Xi summit",
        "context": "Soybeans and other ag commodities; figure announced by US side following May 15-16 Beijing meeting.",
        "source": "Bloomberg, citing US officials post-summit (May 17 2026)",
    }

    # Δ Since Yesterday
    cny_d = mi.get("usd_cny", {}).get("change_pct")
    sse_d = mi.get("sse", {}).get("change_pct")
    hsi_d = mi.get("hsi", {}).get("change_pct")
    brent_d = mi.get("brent", {}).get("change_pct")
    delta_items = []
    if sse_d is not None:
        delta_items.append(f"SSE {'+' if sse_d >= 0 else ''}{sse_d:.2f}%")
    if hsi_d is not None:
        delta_items.append(f"HSI {'+' if hsi_d >= 0 else ''}{hsi_d:.2f}%")
    if cny_d is not None:
        delta_items.append(f"USD/CNY {'+' if cny_d >= 0 else ''}{cny_d:.2f}%")
    if brent_d is not None:
        delta_items.append(f"Brent {'+' if brent_d >= 0 else ''}{brent_d:.2f}%")
    if len(gray_zone) > 0:
        delta_items.append(f"{len(gray_zone)} gray-zone RSS hits")
    if xi_appeared:
        delta_items.append("Xi appeared")

    digest = {
        "digest_date": "Monday, May 18, 2026",
        "re_line": re_line,
        "market_indicators": markets_for_render,
        "delta_since_yesterday": {"items": delta_items},
        "morning_memo": morning_memo,
        "top_stories": top_stories,
        "overnight_items": overnight,
        "also_today": also,
        "business_economy": business,
        "indo_pacific": indo_pacific,
        "opeds_today": opeds,
        "academic_today": academic,
        "prc_government": prc_gov,
        "calendar_watch": calendar_watch,
        "key_stat": key_stat,
        "monitored_locations": monitored,
        "xinhua_delta": xinhua_delta,
        "sanctions_status": {
            "line": "OFAC SDN-China / BIS Entity List / DoD 1260H · Trackers populated by digest.py from BIS, Treasury, and DoD primary sources",
        },
    }

    with open("test_digest.json", "w") as f:
        json.dump(digest, f, indent=2, ensure_ascii=False)

    print(f"✅ Built test_digest.json")
    print(f"   • Top Stories: {len(top_stories)}")
    print(f"   • Business & Economy: {len(business)}")
    print(f"   • Indo-Pacific: {len(indo_pacific)}")
    print(f"   • Overnight Flash: {len(overnight)}")
    print(f"   • Also Today: {len(also)}")
    print(f"   • Op-Eds: {len(opeds)}")
    print(f"   • PRC Government: {len(prc_gov)}")
    print(f"   • Calendar: {len(calendar_watch)}")
    print(f"   • Monitored locations: {len(monitored)} ({sum(1 for l in monitored if l['status']!='normal')} flagged)")
    print(f"   • Xi appeared: {xi_appeared}")


if __name__ == "__main__":
    build()
