"""The recurring China calendar, computed rather than remembered.

Upcoming is generated by the model from a list of dates in the prompt, which
goes stale. Told to produce events from an exhausted list a model invents
them; told not to invent, it produces none. Korea shipped both failures before
this module existed there.

Recurring dates do not need a model at all. National Day is 1 October every
year. The party's founding is 1 July. These are arithmetic, so they are
computed here and merged with whatever dated events the model found in today's
articles. A date from this file cannot be wrong about the year, because it is
derived from today's date rather than recalled.

What is deliberately NOT here: anything that moves. The NPC and CPPCC sessions,
plenums, LPR settings and summit dates shift or are announced late, so they
must come from an article that states them. The lunar new year moves too, and
is therefore absent: a fixed Gregorian anniversary is safe to compute; a
scheduled or lunar-dated event is not.
"""
from __future__ import annotations

from datetime import date, timedelta

# (month, day, headline, detail). Fixed observances only — nothing that can be
# rescheduled. Keep this list short and certain; it is the floor, not the
# whole calendar.
RECURRING: list[tuple[int, int, str, str]] = [
    (1, 1, "New Year's Day", "PRC public holiday."),
    (4, 15, "National Security Education Day",
     "Marks the 2015 national security law. Ministry of State Security "
     "messaging clusters here."),
    (5, 1, "Labour Day", "PRC public holiday."),
    (5, 4, "Youth Day", "1919 May Fourth Movement anniversary."),
    (6, 4, "Tiananmen anniversary",
     "1989. Censorship tightens and Hong Kong and overseas commemorations draw "
     "official reaction."),
    (7, 1, "CCP founding anniversary",
     "Party founded 1921. Set-piece speeches fall here."),
    (7, 1, "Hong Kong handover anniversary",
     "1997. National Security Law enforcement statements often land on it."),
    (8, 1, "PLA founding anniversary (Army Day)",
     "1927 Nanchang uprising. Capability displays and promotions cluster here."),
    (9, 3, "Victory over Japan anniversary",
     "1945. Parades have been held on round anniversaries."),
    (9, 18, "Mukden Incident anniversary",
     "1931. Anti-Japan commemoration; air-raid sirens in northeastern cities."),
    (10, 1, "National Day",
     "PRC founded 1949, opening the Golden Week holiday. Parades on round "
     "anniversaries."),
    (12, 13, "Nanjing Massacre national memorial day",
     "1937. State ceremony; Japan policy commentary clusters here."),
]

_MONTHS = ("Jan", "Feb", "Mar", "Apr", "May", "Jun",
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")


def _next_occurrence(month: int, day: int, today: date) -> date:
    """The next time this month/day falls, today included."""
    for year in (today.year, today.year + 1):
        try:
            candidate = date(year, month, day)
        except ValueError:              # 29 February in a common year
            continue
        if candidate >= today:
            return candidate
    return date(today.year + 1, month, day)


def upcoming(today: date | None = None, days: int = 30) -> list[dict]:
    """Recurring observances falling within the window, soonest first.

    Shaped like the model's own calendar_watch items so the renderer needs no
    special case.
    """
    today = today or date.today()
    horizon = today + timedelta(days=days)
    out = []
    for month, day, headline, detail in RECURRING:
        when = _next_occurrence(month, day, today)
        if today <= when <= horizon:
            out.append({
                "month": _MONTHS[when.month - 1],
                "day": when.day,
                "headline": headline,
                "detail": detail,
                "_source": "recurring",
                "_date": when.isoformat(),
            })
    return sorted(out, key=lambda item: item["_date"])


# 60 days, not Korea's 30. Korea has thirteen fixed observances spread evenly
# enough that a month always contains one. This calendar has long gaps — the
# stretch from early September to early November holds none — and a horizon
# that returns nothing for two months defeats the point of computing them.
_HORIZON_DAYS = 60


def merge(model_items: list | None, today: date | None = None,
          days: int = _HORIZON_DAYS, limit: int = 5) -> list[dict]:
    """Combine the model's dated events with the computed observances.

    The model's items come first: an event it found in today's reporting is
    more informative than an anniversary anyone could look up. Recurring dates
    fill the remaining slots so the section is never empty, and are skipped
    when the model already reported the same day.
    """
    today = today or date.today()
    merged: list[dict] = []
    seen_days: set[tuple[str, int]] = set()

    for item in (model_items or []):
        if not isinstance(item, dict):
            continue
        headline = str(item.get("headline") or "").strip()
        if not headline:
            continue
        merged.append(item)
        month = str(item.get("month") or "").strip()[:3]
        try:
            seen_days.add((month, int(item.get("day"))))
        except (TypeError, ValueError):
            pass

    for item in upcoming(today, days):
        if len(merged) >= limit:
            break
        if (item["month"], item["day"]) in seen_days:
            continue
        merged.append(item)

    # A calendar reads in date order. Items the model dated with a month and
    # day sort by that; anything it left undated keeps its position at the end
    # rather than being dropped.
    def _key(item: dict) -> tuple:
        if item.get("_date"):
            return (0, item["_date"])
        month = str(item.get("month") or "").strip()[:3].title()
        try:
            m = _MONTHS.index(month) + 1
            d = int(item.get("day"))
        except (ValueError, TypeError):
            return (1, "")
        return (0, _next_occurrence(m, d, today).isoformat())

    return sorted(merged, key=_key)[:limit]
