"""
Generate SOURCES.md from the feed dictionaries in collect.py, so the source
inventory in the repo can never drift from the code. smoke_test.py fails when
the committed copy is stale.

    python list_sources.py
"""
from urllib.parse import unquote

import collect


def _describe(url: str) -> tuple[str, str]:
    if "news.google.com" in url:
        q = unquote(url.split("q=", 1)[1].split("&", 1)[0]).replace("+", " ")
        edition = "GN zh-CN" if "ceid=CN" in url else "GN zh-TW" if "ceid=TW" in url \
            else "GN zh-HK" if "ceid=HK" in url else "GN en-US"
        return edition, f"`{q}`"
    return "direct RSS", f"`{url}`"


def _table(feeds: dict, tiered: bool) -> list[str]:
    rows = ["| Source | Lang | Route | Query / feed | Fallback |", "| --- | --- | --- | --- | --- |"]
    for src, val in feeds.items():
        url = val[0] if tiered else val
        tier = f" ({val[1]})" if tiered else ""
        route, q = _describe(url)
        lang = "ZH" if src in collect._CHINESE_LANG_SOURCES else "EN"
        fb = "GN fallback" if src in collect._FALLBACK else ""
        rows.append(f"| {src}{tier} | {lang} | {route} | {q} | {fb} |")
    return rows


def build() -> str:
    groups = [
        ("Tier 1: News (24h)", collect.TIER1_FEEDS, False),
        ("Tier 2: Analysis (36h, strict dates)", collect.TIER2_FEEDS, True),
        ("Tier 3: Academic (72h, strict dates)", collect.TIER3_FEEDS, True),
        ("Tier 4: PRC primary and government (48h)", collect.TIER4_FEEDS, False),
        ("Xi appearance tracker (72h)", collect.XI_TRACKER_FEEDS, False),
        ("Hidden Reach (72h)", collect.HIDDEN_REACH_FEEDS, False),
        ("Gray zone (72h)", collect.GRAY_ZONE_FEEDS, False),
    ]
    total = sum(len(f) for _, f, _ in groups)
    zh = len(collect._CHINESE_LANG_SOURCES)
    out = [
        "# Sources",
        "",
        "Generated by `python list_sources.py` from `collect.py`. Do not edit by hand.",
        "",
        f"**{total} feeds** across 7 groups, **{zh} Chinese-language**, "
        f"{len(collect._FALLBACK)} direct feeds with a Google News fallback, "
        f"{len(collect.PRESTIGE_JOURNALISTS)} correspondents on the byline watch-list.",
        "",
        "Routing rules:",
        "",
        "- A direct publisher RSS feed is preferred where one exists: real permalinks, fuller summaries.",
        "- Google News search feeds cover paywalled or feed-less publishers. Their redirect links are",
        "  canonicalised by `resolve.py` before the model sees them; unresolved links are kept, never blanked.",
        "- A direct feed that returns nothing falls back to its Google News query for that run.",
        "- A feed that dies gets rerouted, never deleted. `feed_health.json` counts consecutive empty runs;",
        "  five in a row is reported as dead in the run log and the health check.",
        "- Chinese-language feeds are capped at 12 items each per run; relevance ordering in `digest.py`",
        "  decides what reaches the prompt.",
        "",
    ]
    for title, feeds, tiered in groups:
        out.append(f"## {title} ({len(feeds)})")
        out.append("")
        out.extend(_table(feeds, tiered))
        out.append("")
    out.append("## Prestige outlets (item-level flag)")
    out.append("")
    out.append(", ".join(sorted(collect.PRESTIGE_OUTLET_SOURCES)))
    out.append("")
    out.append("## Byline watch-list")
    out.append("")
    out.append(", ".join(sorted(collect.PRESTIGE_JOURNALISTS)))
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    text = build()
    with open("SOURCES.md", "w", encoding="utf-8") as f:
        f.write(text)
    print(f"SOURCES.md written ({len(text):,} chars)")
